add components, css styling
loganripplinger/protect-cats pull request #1
Opened 2022-03-27 22:55 UTC by BrettKearns

2022-03-27 23:56 UTC, loganripplinger requested changes
All of the .js files should be .jsx

2022-03-28 00:00 UTC, loganripplinger requested changes

2022-03-28 00:00 UTC, loganripplinger commented on src/features/main/Header.js
> +    <div>
React fragment here

2022-03-28 20:50 UTC, BrettKearns commented
Changes have been made. Thank you for your review.

2022-03-28 21:06 UTC, loganripplinger requested changes

2022-03-28 21:06 UTC, loganripplinger commented on src/features/main/Header.js
> +import React from "react";
Forgot to delete this file.

2022-03-28 21:06 UTC, loganripplinger commented on src/features/main/Form.js
> +export function Form() {
Forgot to delete this file.

2022-03-28 21:06 UTC, loganripplinger commented on src/App.js
> +import React from "react";
Forgot to delete this file.

2022-03-29 20:30 UTC, loganripplinger approved these changes

2022-03-30 00:01 UTC, merged

2022-03-30 00:02 UTC, BrettKearns commented
😸